[project]
name = "crewai-mcp-tester"
version = "0.1.0"
description = "CrewAI MCP Tester"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apify>=2.7.2",
    "crewai>=0.157.0",
    "crewai-tools[mcp]>=0.60.0",
]
